### ISSUE TITLE
Import from ISCE2

### ISSUE THREAD

**Issue by stoormgeo** [DinhHoTongMinh/TomoSAR#1]
Hi,
Thanks for sharing you code!
Is it possible to import preprocessed data from ISCE2 instead of SNAP?

**Comment by DinhHoTongMinh** [comment]
I am not familiar with ISCE2 at the moment. But it looks straightforward to implement it. Is ISCE2 product in BIG-ENDIAN format?

**Comment by bjmarfito** [comment]
@stoormgeo and @DinhHoTongMinh, I think you may use the two codes in ISCE2 to prepare the ISCE2 preprocessed data to be ingested in TomoSAR. The codes are make_single_reference_stack_isce and mt_prep_isce. Based on the Youtube video, the process of preparing the data is similar to isce2stamps and please correct me if I am wrong. Please refer to this site: https://github.com/isce-framework/isce2/tree/main/contrib/timeseries/prepStackToStaMPS/bin regarding the codes.

**Comment by DinhHoTongMinh** [comment]
@bjmarfito thanks for the suggestions. I investigate ingest ISCE products.

**Comment by bjmarfito** [comment]
Thank you @DinhHoTongMinh :)

**Comment by stoormgeo** [comment]
@DinhHoTongMinh 
Thx!
