### ISSUE TITLE
Inquiries about TomoSAR

### ISSUE THREAD

**Issue by bjmarfito** [DinhHoTongMinh/TomoSAR#2]
Hi, I am new to TomoSAR. I would like to know what is the meaning of the following parameter nlines?

Then, what is the meaning of the 'select binary input file' on the screenshot below?
![Screenshot 2022-02-14 131506](https://user-images.githubusercontent.com/21336508/153804273-199b38b9-7797-4302-a6ab-1ce1c4f4ec21.jpg)

I am asking these questions because I am planning to use the stack of SLCs I have generated from ISCE2 to be ingested into TomoSAR.

**Comment by DinhHoTongMinh** [comment]
I updated the meaning of nlines. It is azimuth_lines in *.par file. 
The data input should be from the SNAP export STAMPS structure at the moment.

**Comment by bjmarfito** [comment]
Noted on this @DinhHoTongMinh.
