### ISSUE TITLE
Executable permissions for shell scripts

### ISSUE THREAD

**Issue by bjmarfito** [DinhHoTongMinh/TomoSAR#5]
Hi @DinhHoTongMinh,

I would like to request if you can add the executable permissions to the following scripts so I could be able to execute them even on the terminal by just exporting their paths on the bash_profile:

1. mt_prep_snap_comsar
2. mt_prep_snap_psds
3. mt_prep_isce_comsar
4. mt_prep_isce_psds

**Comment by DinhHoTongMinh** [comment]
Hi @bjmarfito, 

Does 'chmod 777 mt_*' work for you ?

**Comment by bjmarfito** [comment]
It worked. Thank you @DinhHoTongMinh
