### ISSUE TITLE
Exceed maximum array size error

### ISSUE THREAD

**Issue by yagmurn** [DinhHoTongMinh/TomoSAR#6]
Hi @DinhHoTongMinh ,

I applied Snap2stamps before. Now I am trying to apply your codes to compare results. 
I have 185 images but when I run the PSDS_main.m, after the SHP family progress I am getting an error as below:
![error](https://user-images.githubusercontent.com/74787162/159851408-372b1ef2-f298-44d1-8c6e-532bd3453f63.PNG)

I changed the CalWin parameter and tried with both of the suggested values. Which parameter should I change?

**Comment by DinhHoTongMinh** [comment]
Hi @yagmurn,

Your RAM (i.e. 16GB) is not enough for the memory allocated. 
You can find more information on 'note on performance' at https://github.com/DinhHoTongMinh/TomoSAR/blob/main/PSDS_ComSAR_README.md

**Comment by DinhHoTongMinh** [comment]
Hi @yagmurn,

I just committed a new upgrade to overcome it. Please check the code. 

ComSAR is much friendly Big Data processing. A rough approximation for ComSAR RAM requirement is 5*Nslc*Nline*Nwidth/2.7e8 (GB). For example, 200 images of 1000x5000 size, 1TB should be allocated for PSDS, but for ComSAR it is just...18.5GB.

Cheers,
Dinh
