### ISSUE TITLE
Error while perform APS correction - ComSAR

### ISSUE THREAD

**Issue by lumirinc** [DinhHoTongMinh/TomoSAR#8]
Hello Everyone,

While performing APS correction I am getting the following error. As such there's not much help from the error massage. If anyone ever faced this error and resolve it kindly guide.

Regards 

>> aps_linear
Set lambda manual in parms_aps! 
Set heading manual in parms_aps! 
   PARM: stamps_processed='y'
Set lambda manual in parms_aps! 
Set heading manual in parms_aps! 
   PARM: hgt_matfile='/home/mirza/PSInSAR/InSAR/Korea/Dongae/desc/Project/INSAR_/hgt2.mat'
Set lambda manual in parms_aps! 
Set heading manual in parms_aps! 
   PARM: ll_matfile='/home/mirza/PSInSAR/InSAR/Korea/Dongae/desc/Project/INSAR_/ps2.mat'
Set lambda manual in parms_aps! 
Set heading manual in parms_aps! 
   PARM: phuw_matfile='/home/mirza/PSInSAR/InSAR/Korea/Dongae/desc/Project/INSAR_/phuw2.mat'
Set lambda manual in parms_aps! 
Set heading manual in parms_aps! 
   PARM: non_defo_flag='n'
**Error using load**
**Unable to find file or directory '/home/mirza/PSInSAR/InSAR/Korea/Dongae/desc/Project/INSAR_/phuw2.mat'.**
**Error in aps_linear (line 92)**
**phuw = load(phuw_matfile);**

**Comment by DinhHoTongMinh** [comment]
@lumirinc 
This is very specific to TRAIN or StaMPS. 
Can you post question in here: 
https://groups.google.com/g/mainsar
or 
https://www.facebook.com/groups/radarinterferometry
